//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditGestionRisqueLesire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3A2Entities : DbContext
    {
        public DBIG3A2Entities()
            : base("name=DBIG3A2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresses { get; set; }
        public virtual DbSet<Assistante> Assistantes { get; set; }
        public virtual DbSet<Assistante_Equipe> Assistante_Equipe { get; set; }
        public virtual DbSet<Compte> Comptes { get; set; }
        public virtual DbSet<Emploi> Emplois { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<EquipeMedicale> EquipeMedicales { get; set; }
        public virtual DbSet<examen_en_fonction_du_risque> examen_en_fonction_du_risque { get; set; }
        public virtual DbSet<examen_particulier> examen_particulier { get; set; }
        public virtual DbSet<ExamenRealise> ExamenRealises { get; set; }
        public virtual DbSet<Interllocuteur> Interllocuteurs { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Lieu> Lieux { get; set; }
        public virtual DbSet<Lieu_Equipe> Lieu_Equipe { get; set; }
        public virtual DbSet<Medecin> Medecins { get; set; }
        public virtual DbSet<MediT> MediTs { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Secteur> Secteurs { get; set; }
        public virtual DbSet<TraductionExaman> TraductionExamen { get; set; }
        public virtual DbSet<TraductionProfession> TraductionProfessions { get; set; }
        public virtual DbSet<TraductionRisque> TraductionRisques { get; set; }
        public virtual DbSet<Travailleur> Travailleurs { get; set; }
        public virtual DbSet<TypeExaman> TypeExamen { get; set; }
        public virtual DbSet<TypeExamen_TypeRisque> TypeExamen_TypeRisque { get; set; }
        public virtual DbSet<TypeRisque> TypeRisques { get; set; }
        public virtual DbSet<VisiteMedicale> VisiteMedicales { get; set; }
    }
}
