//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditGestionRisqueLesire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examen_en_fonction_du_risque
    {
        public decimal IdExamenFonctionRisque { get; set; }
        public decimal IdRisque { get; set; }
        public decimal IdEmploi { get; set; }
    
        public virtual Emploi Emploi { get; set; }
        public virtual TypeRisque TypeRisque { get; set; }
    }
}
