//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditGestionRisqueLesire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenRealise
    {
        public decimal IdExamenRealiser { get; set; }
        public decimal NumeroVisite { get; set; }
        public decimal IdExamen { get; set; }
        public decimal Duree { get; set; }
        public string Resultat { get; set; }
        public decimal PrixTotal { get; set; }
        public string NomMedecin { get; set; }
        public decimal Pou_NumeroVisite { get; set; }
    
        public virtual VisiteMedicale VisiteMedicale { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual TypeExaman TypeExaman { get; set; }
    }
}
