//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditGestionRisqueLesire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediT
    {
        public string Nom { get; set; }
        public decimal Telephone { get; set; }
        public decimal Fax { get; set; }
        public string SiteWeb { get; set; }
        public decimal NumeroCompte { get; set; }
        public decimal PrixRedevanceTravailleurSoumis { get; set; }
        public decimal PrixRedevanceTravailleurNonSoumis { get; set; }
        public Nullable<decimal> IdAdresse { get; set; }
    
        public virtual Adresse Adresse { get; set; }
    }
}
