//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditGestionRisqueLesire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeExaman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeExaman()
        {
            this.examen_particulier = new HashSet<examen_particulier>();
            this.ExamenRealises = new HashSet<ExamenRealise>();
            this.TraductionExamen = new HashSet<TraductionExaman>();
            this.TypeExamen_TypeRisque = new HashSet<TypeExamen_TypeRisque>();
        }
    
        public decimal IdExamen { get; set; }
        public decimal PrixTravailleurSoumis { get; set; }
        public decimal PrixTravailleurNonSoumis { get; set; }
        public decimal IdCompte { get; set; }
    
        public virtual Compte Compte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examen_particulier> examen_particulier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenRealise> ExamenRealises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraductionExaman> TraductionExamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeExamen_TypeRisque> TypeExamen_TypeRisque { get; set; }
    }
}
